version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/rest-api-gin-gorm-sql
    depends_on:
      - database
    container_name: rest-api-test
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: articledb
    container_name: golang-docker-db
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql


  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: golang-docker-pma