version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/rest-api-gin-gorm-sql
    container_name: article-docker-web
    depends_on:
      - database


  database:
    build:
      context: .
      dockerfile: ./db/db.Dockerfile
    environment:
      ##keep the name same
      MYSQL_ROOT_PASSWORD: root
      ##we normally access by root but keep it like this 
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      ##keep the database name what you want to keep
      MYSQL_DATABASE: articledb
    ##this will be the name of the container that you want to create
    container_name: article-docker-db
    ports:
      - 33066:3306


  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: article-docker-pma
    
    
      



